name: ${rootproject.name}
version: ${project.version}
author: RoboSky
depend:
- Vault
- PlaceholderAPI
softdepend: []
main: skychat.SkyChatSpigot
commands:
    msg:
        usage: /msg [player] [msg]
        description: Send a private message to a player
        permission-message: You don't have <permission>
    afk:
        usage: /afk
        description: Toggle afk mode
        permission-message: You don't have <permission>
    me:
        usage: /me [msg]
        description: Send an action message
        permission-message: You don't have <permission>
    r:
        usage: /r [msg]
        description: Reply to a player
        permission-message: You don't have <permission>