name: ${project.name}
version: ${project.version}
author: RoboSky
depend:
- Vault
- PlaceholderAPI
softdepend: []
main: skychat.SkyChatSpigot
commands:
    msg:
        usage: /msg [player] [msg]
        description: Send a private message to a player
        aliases: ['/w']
    afk:
        usage: /afk
        description: Toggle afk mode
    me:
        usage: /me [msg]
        description: Send an action message
    r:
        usage: /r [msg]
        description: Reply to a player
        aliases: ['/reply']